### ISSUE TITLE
Icons fail to load

### ISSUE THREAD

**Issue by sarahboyce** [django/djangoproject.com#1881]
Noticed that icons are not loading on djangoproject.com (at least for me: on desktop, firefox, on mobile Chrome, Android).
They work on code.djangoproject.com and docs.djangoproject.com for mobile, they work in incognito mode 👍

Errors:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://docs.djangoproject.com’).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://docs.djangoproject.com’).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0
```

![Image](https://github.com/user-attachments/assets/dbbe7252-8c44-4ef4-84d0-4c4ea87e88e8)

<details><summary>Screenshots with broken icons</summary>

Desktop:

![Desktop icons fail to load](https://github.com/user-attachments/assets/5093f791-ffec-49b8-adc7-63e684ac1ed5)

Mobile:

![home page icons failed to load](https://github.com/user-attachments/assets/c12b2dd9-6430-4a2d-972e-f4fcaeceae60)

</details>

**Comment by pauloxnet** [comment]
> Noticed that icons are not loading on djangoproject.com on mobile (at least for me: Chrome, Android).

I can see icons on mobile 👍 

I tested the website with Android 15 on Pixel 7
- Chrome 132
- Firefox 134

@sarahboyce what version of Phone/OS/Browser are you experiencing the issue?

**Comment by sarahboyce** [comment]
Android 14, Chrome 132

**Comment by nessita** [comment]
> I still have this with cleared cache, it's been this way for a few days

Is it the same if you try an incognito window or another browser like Firefox? I can't reproduce either 🤔

**Comment by sarahboyce** [comment]
Works on incognito 👍
This issue also is fine with incognito: https://github.com/django/djangoproject.com/issues/1887
So perhaps resolving those errors will resolve both issues for me

**Comment by adamzap** [comment]
Ah, given your comment in #1887, it seems like a production configuration issue, right? I wonder why it's not happening for the rest of us though.

**Comment by adamzap** [comment]
Since the discussion seems to be happening here, this is @sarahboyce's comment from #1887 showing the console errors related to this issue:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://docs.djangoproject.com’).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://docs.djangoproject.com’).

downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://static.djangoproject.com/fonts/fontawesome-webfont.d95d6f5d5ab7.woff?v=4.2.0 
```

The asset URL works fine for me. It's odd to me that `https://docs.djangoproject.com` is referenced here. I wonder if there is some host confusion happening?

For what it's worth, this header seems a bit odd to me too, but I should revisit the docs:

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/c767d931-b69b-42f9-b488-2d805c8948b6" />

Anyway, these are just initial ideas. I hope to have some time later this week to debug this if the solution is not obvious to someone else.

**Comment by sarahboyce** [comment]
I added a screenshot of the broken link for me and this is cached until Dec 2037. I wonder if @bmispelon can do anything here 🤔

**Comment by bmispelon** [comment]
This is definitely confusing 🤔 

In case that helps, here's the relevant (I think) portion of the nginx configuration for `static.djangoproject.com`:
```
map $http_origin $sanitized_origin {
	"~*^https://.+\.djangoproject\.com$"	$http_origin;
	default static.djangoproject.com;
}

server {
	listen [::]:443 ssl;
	server_name static.djangoproject.com;

	location / {
		gzip on;
		gzip_vary on;
		alias /var/www/static/;
		if ($uri ~* ".*\.[a-f0-9]{12,}\.(css|js|png|jpg|jpeg|gif|ico|woff|ttf|otf|svg|scss|map|txt)" ) {
			expires max;
		}
		include /etc/nginx/security_headers;
		# The 'Origin:' header will be set by browsers when requesting
		# fonts, etc. Tell the browser to allow such requests only on
		# HTTPS, from any subdomain of djangoproject.com.
		add_header "Access-Control-Allow-Origin" $sanitized_origin;
		add_header "Vary" "Origin";
	}
}
```

It seems that the response you're receiving have the wrong `Access-Control-Allow-Origin` header set on them. Unfortunately, your first screenshot doesn't show the value (you have to scroll a little further up in the response headers). Can you report on the value of the `Access-Control-Allow-Origin` response header on the response that is blocked by CORS?

**Comment by sarahboyce** [comment]
> Can you report on the value of the Access-Control-Allow-Origin response header on the response that is blocked by CORS?

`https://docs.djangoproject.com/`

**Comment by sarahboyce** [comment]
Cleared my cache on firefox, desktop this morning and the error is gone and icons load. I know have the correct `Access-Control-Allow-Origin` 🥳 

Clearing the cache isn't working on mobile, I don't have access to errors to see what is going on there 🤔

**Comment by sarahboyce** [comment]
Ah there's a "filter" on clearing data on mobile to only do the last 24 hours 🤦 
I have now "blitzed" the cache and it is working on mobile. I'm not sure what happened but I imagine it was a temporary issue and if not, can always reopen 👍

**Comment by bmispelon** [comment]
I think I managed to reproduce the issue consistently with these steps (using Firefox on desktop):

1) Clear cache
2) Visit www.djangoproject.com
3) Visit https://docs.djangoproject.com/en/5.1/intro/install/ (or any page that contains icons)

When doing that, the icon that should be in the green box "Always refer to the documentation that corresponds to the version of Django you’re using!" is missing and replaced by a square box with 4 letters.

My best understanding of the bug is that the browser is caching the font alongside the `Access-Control-Allow-Origin`, then refusing to reuse the font on a different domain than the original response. If that's correct I'm not sure whether that's a browser bug, or a misconfiguration on our end 🤔

**Comment by bmispelon** [comment]
I wonder if this might be the issue we're seeing: https://stackoverflow.com/questions/44800431/caching-effect-on-cors-no-access-control-allow-origin-header-is-present-on-th

If so, the fix suggested in the top answer is to tweak the `Vary` header (in the server config):
`Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method`

I'll try that config change later today and see if that helps.

**Comment by adamzap** [comment]
@bmispelon Good find! Are you getting this on the document response when you go to https://www.djangoproject.com/ ?

<img width="585" alt="Image" src="https://github.com/user-attachments/assets/3deed4b0-c096-4501-a8cf-b66f5329853c" />

Does that seem correct?

**Comment by sarahboyce** [comment]
> I think I managed to reproduce the issue consistently with these steps (using Firefox on desktop):
> 
>     1. Clear cache
> 
>     2. Visit [www.djangoproject.com](http://www.djangoproject.com)
> 
>     3. Visit https://docs.djangoproject.com/en/5.1/intro/install/ (or any page that contains icons)
> 

🎉 yes, this is it.
My icons broke again for me though being on a mixture of docs.djangoproject.com and www.djangoproject.com

**Comment by bmispelon** [comment]
The fix I did with the headers appears to be live (I even cleared the fastly cache), but unfortunately it doesn't seem to have fixed anything 😿

**Comment by adamzap** [comment]
I'm not sure if I'm reading the docs ([1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), [2](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)) correctly, but I'm trying to understand why this header is helpful on the site at all. Is anyone sure?

**Comment by apollo13** [comment]
@bmispelon The browser is caching the request. Can you try removing the etag (`etag off;` in that section is probably enough) and clear the fastly cache again?

**Comment by apollo13** [comment]
@bmispelon Got a better idea, can you try setting `add_header "Access-Control-Allow-Origin" $sanitized_origin always;` (note the added `always` at the end) and then clear the fastly cache, then I can look into my browser logs again.

**Comment by apollo13** [comment]
@adamzap 

> I'm not sure if I'm reading the docs ([1](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), [2](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)) correctly, but I'm trying to understand why this header is helpful on the site at all. Is anyone sure?

It is required to load the woff files at all which are subject to CORS. But simply allowing `*` might be okay (I don't remember why we decided against it -- maybe the fonts are licensed and we are required to ensure that they can only be loaded from our pages).

**Comment by apollo13** [comment]
I have thought more about this. Even if we were to get the current approach working the browser would probably still recheck the font files when switching between docs & www. As such I recommend settings `Access-Control-Allow-Origin` to `*` which will effectively fix this and also prevent the revalidations.

**Comment by adamzap** [comment]
@apollo13 For what it's worth, this makes sense to me as well. I don't think we need to lock things down with this header.

**Comment by adamzap** [comment]
This should not have been closed by #1949...or was it actually fixed at the ops level?

**Comment by adamzap** [comment]
I'm not getting Roboto consistently on the production site, probably because of this issue. I mentioned in #1949 that we should address this issue before merging/deploying self-hosted fonts.

Let me know if there's anything I can do to help address this!

**Comment by laymonage** [comment]
Same here. I see the font-face declarations for Roboto are missing in place where I'd expect them to be:

<img width="1147" alt="Image" src="https://github.com/user-attachments/assets/ef7e2580-9624-4fd0-b513-62b3ec85eb81" />

I'm not sure if it's the same issue, but it does seem to be caching/CDN related because the code is already there: 

https://github.com/django/djangoproject.com/blob/2b81daed2fc34c3a92fd973781768f247b2e40bd/djangoproject/scss/_utils.scss#L46-L95

Switching browsers and using incognito did not work.

**Comment by bmispelon** [comment]
> I'm not sure if it's the same issue, but it does seem to be caching/CDN related because the code is already there:

This is super weird and I don't really understand how it's possible. What seems to have happened is that we served the page with the new version of `base.html` (the one where the `<link>`s have been removed) but the old version of `output.css` (you can see the hash is `4bab36a7ad8a` when it should be `7ae60ccd2c72`). And that page with now broken fonts managed to be cached by Fastly. I wonder if it's the same issue that causes a bunch of errors on Sentry when we deploy changes that move/delete a static file (we're tracking this internally on the ops team but haven't made progress) 🤔 

In any case, this should resolve itself once the cache clears. You can get get a non-cached version of the page by appending `?some_random_string` to the end of the URL and you should see the correct font there.

So that was a real issue, but separate from the original one 😁

**Comment by apollo13** [comment]
> What seems to have happened is that we served the page with the new version of base.html (the one where the <link>s have been removed) but the old version of output.css (you can see the hash is 4bab36a7ad8a when it should be 7ae60ccd2c72).

@bmispelon I can imagine that happening if collectstatic isn't executed before the server starts in which case the staticfiles manifest might still have old data?

**Comment by adamzap** [comment]
@tobiasmcnulty For what it's worth, font and icon assets are fixed for me!

**Comment by laymonage** [comment]
I can confirm that the font loads properly for me too. (And the icons for that matter, but I don’t remember whether I had that issue or not.)

**Comment by apollo13** [comment]
@tobiasmcnulty `access-control-allow-origin https://www.djangoproject.com/` in the response headers is still there, so icons will still fail to load when switching domains (see https://github.com/django/djangoproject.com/issues/1881#issuecomment-2643280458).

**Comment by tobiasmcnulty** [comment]
@apollo13 I see, I can indeed reproduce that if I step away for a bit and come back. A force reload fixes it.

We can change the header as you suggested, or even move away from the static.dp.com domain in favor of building the assets into the image and serving them with gunicorn. Everything is behind Fastly now, so the separate domain and build step feel like unnecessary complexity. What do you think?

**Comment by tobiasmcnulty** [comment]
I changed the header so we can see if that fixes it:

```
❯ curl -I https://static.djangoproject.com/fonts/Roboto-Light.4b97d1da126a.woff2 2>/dev/null | grep access
access-control-allow-origin: *
```

Either way, I'd still be grateful for any feedback on the `/static/` approach (i.e., sunsetting static.dp.com).

**Comment by adamzap** [comment]
If the separate domain isn't benefitting the site, I don't see the point in keeping it. I'm not on the ops team though, so I don't know all the details.

**Comment by apollo13** [comment]
Getting rid of the static subdomain makes sense if www. and docs. don't share a Cache in the browser because then you'd download the font etc twice anyways. If they share one (which I somewhat suspect) then the subdomain is good (will check later whether they share the cache entry or not).

**Comment by tobiasmcnulty** [comment]
@apollo13 Good point, yes, they do share the browser cache (wasn't that the issue?). In fact, I still had a stray font in my browser cache with the old header this morning, and it didn't load for me until after a force-refresh.

@adamzap @bmispelon Perhaps we should also change [$font-path](https://github.com/django/djangoproject.com/blob/main/djangoproject/scss/_utils.scss#L42) or add a query string to each font path to force browsers to reload the fonts now that the header is changed? They are set to cache forever, so until the path changes or they are force-reloaded, I think browsers will happily continue using their local copy.

```
❯ curl -I https://static.djangoproject.com/fonts/Roboto-Light.4b97d1da126a.woff2 2>/dev/null | grep cache-control
cache-control: max-age=315360000
```

**Comment by apollo13** [comment]
> @apollo13 Good point, yes, they do share the browser cache (wasn't that the issue?). In fact, I still had a stray font in my browser cache with the old header this morning, and it didn't load for me until after a force-refresh.

Ah yes, I have lost track of what is cached where now :D

**Comment by adamzap** [comment]
@tobiasmcnulty That's a good idea. I can think of two approaches that should both create a cache invalidation for users and maybe even increase consistency in our static assets:

1. Change `$font-path` from `../fonts` to `../font` and rename the directory. This would be more consistent with `/static/img/`
2. Rename the font files to be all lowercase.

We could also just add `?v2` at the end of the font asset filenames, but that seems a bit more esoteric to me. I'm not strongly against it though.

@bmispelon Any thoughts? I'd be happy to open a PR for this once we decide on an approach. I may lean toward doing both of the renaming changes above, but I defer to you.

**Comment by bmispelon** [comment]
@adamzap All these should have the same cache-busting effect indeed. I'd say option 1 is marginally better, since it requires the least amount of change I believe.

**Comment by bmispelon** [comment]
I've deployed the changes suggested by Tobias in https://github.com/django/djangoproject.com/issues/1881#issuecomment-2706402970 (thanks to a fast response by Adam).

As far as I can tell, this issue is now completely fixed, no?

**Comment by adamzap** [comment]
Looks good to me so far!

**Comment by adamzap** [comment]
I'm going to close this. Please reopen it if the problem happens again.
